name = "rusty-edge"
main = "build/worker/shim.mjs"
compatibility_date = "2022-01-20"

[vars]
MY_ENV_VAR = "w00t"

[build]
command = "cargo install -q worker-build --version 0.0.7 && worker-build --release"
